/**
 * Auto-generated sidebar — Docusaurus builds the sidebar from the
 * front matter (`sidebar_position`, `sidebar_label`) and `_category_.json`
 * files inside `docs/`. So there is nothing to maintain by hand here.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
module.exports = {
  defaultSidebar: [{ type: "autogenerated", dirName: "." }],
};