import React from 'react';
import styled from 'styled-components';
import Helmet from 'react-helmet';
import { StaticQuery, graphql } from 'gatsby';
import '../css/layout.css'

const Masthead = styled.header`
    
`;
const Section = styled.section`
    
`;

const Footer = styled.footer`
  
`;

function Layout({ children, title }) {

  return (
    <StaticQuery
      query={graphql`
        query SiteTitleQuery {
          site {
            siteMetadata {
              title
            }
          }
        }
      `}
      render={data => (
        <>
          <Helmet title={`${title} | ${data.site.siteMetadata.title}`}>
            <html lang="en" />
          </Helmet>
          <Masthead>{data.site.siteMetadata.title}</Masthead>
          
          <Section className="wrapper">{children}</Section>
          <Footer>
            <p>
              Generated by{' '}
              <a href="https://github.com/intuitiva/docs-zauru">
                Zauru Documentation
              </a>
            </p>
            <p>
              Made by <a href="https://www.intuitiva.solutions">Lester Guerra</a>
            </p>
          </Footer>
        </>
      )}
    />
  );
}

export default Layout;
