#!/usr/bin/env node
/**
 * import_tutorials.mjs — Crea la base rag (si no existe), la tabla data
 * y carga los Markdown de docs/ sin frontmatter.
 *
 * Uso:
 *   node import_tutorials.mjs
 *   bun import_tutorials.mjs
 *   DOCS_PATH=/ruta/a/docs node import_tutorials.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import pg from 'pg';

const { Client } = pg;

const toolDir = import.meta.dirname;
const repoRoot = path.resolve(toolDir, '../..');

loadEnv(path.join(toolDir, '.env'));

function loadEnv(envPath) {
  if (!fs.existsSync(envPath)) return;
  if (typeof process.loadEnvFile === 'function') {
    process.loadEnvFile(envPath);
    return;
  }
  for (const rawLine of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    if (/^[A-Z0-9_]+$/.test(key) && process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

function env(name, fallback) {
  const value = process.env[name];
  if (value === undefined || value.length === 0) return fallback;
  return value;
}

function quoteIdent(identifier) {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier)) {
    throw new Error(`Identificador SQL inválido: ${identifier}`);
  }
  return `"${identifier}"`;
}

function stripFrontmatter(content) {
  const lines = content.split('\n');
  if (lines[0]?.trim() !== '---') return content;

  for (let i = 1; i < lines.length; i++) {
    if (lines[i]?.trim() === '---') {
      return lines
        .slice(i + 1)
        .join('\n')
        .replace(/^\n+/, '');
    }
  }

  return content;
}

async function collectMarkdown(docsPath) {
  const results = [];

  async function walk(dir) {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
        continue;
      }
      if (entry.isFile() && entry.name.endsWith('.md')) {
        const relPath = path.relative(docsPath, fullPath).split(path.sep).join('/');
        results.push({ fullPath, relPath });
      }
    }
  }

  await walk(docsPath);
  results.sort((a, b) => a.relPath.localeCompare(b.relPath));
  return results;
}

function clientConfig(database) {
  const password = process.env.PGPASSWORD;
  return {
    host: process.env.PGHOST || undefined,
    port: Number(env('PGPORT', '5432')),
    user: env('PGUSER', 'finanzas'),
    password: password === undefined || password.length === 0 ? undefined : password,
    database,
  };
}

async function ensureDatabase(database) {
  const admin = new Client(clientConfig(env('PGADMIN_DATABASE', 'postgres')));
  await admin.connect();
  try {
    const existing = await admin.query('SELECT 1 FROM pg_database WHERE datname = $1', [database]);
    if ((existing.rowCount ?? 0) > 0) {
      console.log(`Base de datos existente: ${database}`);
      return;
    }
    await admin.query(`CREATE DATABASE ${quoteIdent(database)}`);
    console.log(`Base de datos creada: ${database}`);
  } finally {
    await admin.end();
  }
}

const SCHEMA_SQL = `
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS data (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path text NOT NULL,
  tutorial text NOT NULL,
  embedding vector(1024),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE data
  ALTER COLUMN embedding TYPE vector(1024);

CREATE UNIQUE INDEX IF NOT EXISTS data_path_uidx ON data (path);
CREATE INDEX IF NOT EXISTS data_tutorial_trgm_idx ON data USING gin (tutorial gin_trgm_ops);
`;

const UPSERT_SQL = `
INSERT INTO data (path, tutorial, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (path) DO UPDATE
SET tutorial = EXCLUDED.tutorial,
    updated_at = EXCLUDED.updated_at,
    embedding = CASE
      WHEN data.tutorial IS DISTINCT FROM EXCLUDED.tutorial THEN NULL
      ELSE data.embedding
    END
`;

async function main() {
  const database = env('PGDATABASE', 'rag');
  const docsPath =
    process.env.DOCS_PATH !== undefined && process.env.DOCS_PATH.length > 0
      ? path.resolve(process.env.DOCS_PATH)
      : path.join(repoRoot, 'docs');

  if (!fs.existsSync(docsPath)) {
    throw new Error(`No existe la carpeta de documentación: ${docsPath}`);
  }

  await ensureDatabase(database);

  const client = new Client(clientConfig(database));
  await client.connect();
  try {
    await client.query(SCHEMA_SQL);

    const files = await collectMarkdown(docsPath);
    if (files.length === 0) {
      throw new Error(`No se encontraron archivos .md en ${docsPath}`);
    }
    console.log(`Encontrados ${files.length} archivos .md`);

    await client.query('BEGIN');
    try {
      const paths = [];
      for (const file of files) {
        const raw = await fs.promises.readFile(file.fullPath, 'utf8');
        const tutorial = stripFrontmatter(raw);
        const fileStat = await fs.promises.stat(file.fullPath);
        await client.query(UPSERT_SQL, [file.relPath, tutorial, fileStat.mtime]);
        paths.push(file.relPath);
        console.log(`Insertado: ${file.relPath}`);
      }

      await client.query('DELETE FROM data WHERE NOT (path = ANY($1::text[]))', [paths]);
      await client.query('COMMIT');
      console.log(`Listo: ${paths.length} tutoriales en ${database}.data`);
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    }
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
